{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Release.Name }}
    component: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  # PostgreSQL password stored securely in secret
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
{{- end }}
