{{- if .Values.logs.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-logs
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: logs
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.logs.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.logs.persistence.size }}
{{- end }}
