apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  # Base64 encoded values
  # Default: airflow
  fernet-key: {{ "airflow" | b64enc }}
  webserver-secret-key: {{ "airflow_secret_key" | b64enc }}
