apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-webserver
  labels:
    app: {{ .Chart.Name }}
    component: webserver
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  {{- with .Values.webserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
  - port: {{ .Values.webserver.service.port }}
    targetPort: webserver
    protocol: TCP
    name: webserver
  selector:
    app: {{ .Chart.Name }}
    component: webserver
